DELETE FROM [DenmarkMapsDB].[dbo].[member]
DELETE FROM [DenmarkMapsDB].[dbo].[relation_tags]
DELETE FROM [DenmarkMapsDB].[dbo].[relation]
DELETE FROM [DenmarkMapsDB].[dbo].[way_nodes]
DELETE FROM [DenmarkMapsDB].[dbo].[way_tags]
DELETE FROM [DenmarkMapsDB].[dbo].[way]
DELETE FROM [DenmarkMapsDB].[dbo].[node_tags]
DELETE FROM [DenmarkMapsDB].[dbo].[node]
